eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO
    root: INFO
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: belt-service
        uri: lb://belt-service
        predicates[0]: Path=/api/belts
      routes[1]:
        id: badge-service
        uri: lb://badge-service
        predicates[0]: Path=/api/badges
      routes[2]:
        id: award-service
        uri: lb://award-service
        predicates[0]: Path=/api/awards
      routes[3]:
        id: discovery-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[4]:
        id: discovery-server-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
  main:
    web-application-type: reactive
server:
  port: 8080
